### ISSUE TITLE
I still don't see "Hosted by"

### ISSUE THREAD

**Issue by SGAHJDGAJHDGSA** [Androz2091/giveaways-bot#10]
I have looked at how you have done it in the start.js file. I added that to my project, but when I start a giveaway I get this: 
<img width="244" alt="Screen Shot 2020-02-17 at 2 19 52 PM" src="https://user-images.githubusercontent.com/60992962/74681127-9a0e7280-5190-11ea-9a4b-91dfa9b4f49a.png">

**Comment by Androz2091** [comment]
@SGAHJDGAJHDGSA did you update your config file?

**Comment by Zaid-maker** [comment]
@Androz2091 you have not added in the config file too.

**Comment by Androz2091** [comment]
Uh. You're right. Added.

**Comment by SGAHJDGAJHDGSA** [comment]
Yes I have added "hostedBy" in my config and this is what I get 
<img width="308" alt="Screen Shot 2020-02-18 at 2 47 25 PM" src="https://user-images.githubusercontent.com/60992962/74772280-aca2ad80-525d-11ea-919d-b02e14cbf9ba.png">

This is what is in my config:
`{
    "token" : "my token",
    "prefix" : "o!",
    "everyoneMention": false,
    "hostedBy": true
}`

**Comment by Androz2091** [comment]
You also have to update `discord-giveaways`. Run `npm install discord-giveaways`.

**Comment by SGAHJDGAJHDGSA** [comment]
ah i see

**Comment by Androz2091** [comment]
Does it appear now?

**Comment by Zaid-maker** [comment]
@SGAHJDGAJHDGSA  PLEASE CLOSE THE ISSUE IT IS SOLVED NOW. THANK YOU
