### ISSUE TITLE
Hiw do i use non-unicode emojis?

### ISSUE THREAD

**Issue by d86592** [Androz2091/giveaways-bot#13]
I can’t use any custom emojis from my server for the giveaway. It will react but it won’t add them to the giveaway. I host this on glitch and customized it slightly.

**Comment by Androz2091** [comment]
Custom reactions aren't supported for the moment. It's a planned feature

**Comment by Androz2091** [comment]
An issue is actually opened here https://github.com/Androz2091/discord-giveaways/issues/29 to support this feature.

**Comment by Androz2091** [comment]
Added!
