### ISSUE TITLE
guildid parameter

### ISSUE THREAD

**Issue by Pcarlo01** [Androz2091/giveaways-bot#14]
When we try to have all the giveaway oof the servers from the documentation ( https://www.npmjs.com/package/discord-giveaways)

let onServer = client.giveawaysManager.giveaways.filter((g) => g.guildID === "the guild id ");

We don't have in the json file the parameter guildID so it doesn't work.

**Comment by Androz2091** [comment]
Fixed. Run `npm install discord-giveaways` to update the package. Thank you for reporting the bug!
