### ISSUE TITLE
Mention role (@giveaways) instead of @everyone.

### ISSUE THREAD

**Issue by drje** [Androz2091/giveaways-bot#15]
I have tried multiple changes to have the bot ping just the role @giveaways instead of @everyone but nothing I have done has worked. What would be the best way to change this?

Thanks in advance.

**Comment by Huskydog9988** [comment]
If your editing the code, and only plan to use it on your server, you can do the following: replace `@everyone` in the code with `<@(ROLE ID HERE)>` and make sure to replace `(ROLE ID HERE)` with the id of the role `@giveaways`.

**Comment by Androz2091** [comment]
Hello,
The only way to do that actually is the way described by @Huskydog9988. Here are a few more details:

* Open the file `commands/start-giveaways.js`
* Edit this line https://github.com/Androz2091/giveaways-bot/blob/master/commands/start-giveaway.js#L50
* Replace @everyone by `<@&ROLEID>` (replace `ROLEID` with the ID of your role).

**Comment by Huskydog9988** [comment]
Thank you for clarifying, also I completely forgot about the `&`. That could have really messed someone up.
