### ISSUE TITLE
Giveaway cancelled, no valid participations.

### ISSUE THREAD

**Issue by Tehttt** [Androz2091/giveaways-bot#16]
It keeps saying Giveaway cancelled, no valid participations. when 9 people enter and the giveaway ends

**Comment by Androz2091** [comment]
@Tehtt are you sure people aren't administrators or moderators?

**Comment by snowdqdzq** [comment]
J'ai le même problème et le bot est administrateur :/

**Comment by Androz2091** [comment]
@snowdqdzq est-ce que tu es sur que tous les participants ne sont pas admins?

**Comment by snowdqdzq** [comment]
Hey! Merci de me répondre aussi rapidement, et sa marche merci :)

**Comment by Androz2091** [comment]
Parfait, bonne journée
