### ISSUE TITLE
Issue With manager

### ISSUE THREAD

**Issue by TFPO** [Androz2091/giveaways-bot#18]
when i go to use the start giveaway command i get this error `
[2020-03-17 02:06:54] Uncaught Promise Error:
[2020-03-17 02:06:54] The manager is not ready yet.`

any reason i would be getting this?

**Comment by Androz2091** [comment]
Hmm that's weird... Can you wait ~10 seconds after the bot shows it's ready and run the start command?

**Comment by Zaid-maker** [comment]
Yea It should work as you tell you have to wait, or restart you editor this will fix.

**Comment by Zaid-maker** [comment]
@Androz2091  He's right the manager is not ready

**Comment by sysysysy242** [comment]
pls i have this error to

**Comment by Ungkimyou** [comment]
(node:8097) UnhandledPromiseRejectionWarning: The manager is not ready yet.

(node:8097) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

**Comment by Androz2091** [comment]
@Ungkimyou can you check if there is another error before this one please?

**Comment by Zaid-maker** [comment]
@Androz2091  This is the only error we all getting.

**Comment by Zaid-maker** [comment]
@Ungkimyou  @sysysysy242 @TFPO  I found the problem the actual is with giveaways.json file where all of our giveaways store delete it and restart the bot it should fix the error.
