### ISSUE TITLE
@everyone mention 

### ISSUE THREAD

**Issue by FFFFFFFFFFFFFFF13** [Androz2091/giveaways-bot#2]
When someone starts a giveaway it mentions everyone.. how can i remove the @everyone mention?

**Comment by Androz2091** [comment]
Actually, that's not possible but I can develop it

**Comment by Zaid-maker** [comment]
Like I mean to say that without using the message if to end the giveaway why not we use giveaway name to end it.

**Comment by Androz2091** [comment]
I think it was to answer that question? (#1) If so, that's possible yes

**Comment by Zaid-maker** [comment]
ok Thank you so Much if you did this because i want my bot on top.gg i already one but i want this that i made with your package.

**Comment by Zaid-maker** [comment]
Please make more updates to this package it's really good

**Comment by Androz2091** [comment]
This isn't a package repository, right? ^^
The repository for `discord-giveaways` is here: https://github.com/Androz2091/discord-giveaways.

**Comment by Zaid-maker** [comment]
Yeah I forget but nice work man۔
Yo know you are the second developer I follow when I  joined GitHub and I also managed your AtlantaBot in my free time۔

**Comment by Androz2091** [comment]
👌 thank you

**Comment by HusnainJatoi** [comment]
Ok nice!! when you fully develop that ^^ then please inform me.

Discord Username: Husnain Jatoi#5977
Email: mianhusnainjatoi@gmail.com
