### ISSUE TITLE
cmd.message is not a function

### ISSUE THREAD

**Issue by SrPeterr** [Androz2091/giveaways-bot#26]
Hi!
Im getting an error everytime I want to start a giveaway...
```
TypeError: cmd.run is not a function
    at module.exports (/home/SrDiscord/events/sorteos/message.js:19:9)
    at Client.emit (events.js:322:22)
    at MessageCreateAction.handle (/home/SrDiscord/node_modules/discord.js/src/client/actions/MessageCreate.js:31:4)
```

My message.js:
```
module.exports = (client, message) => {
    // Ignore all bots
    if (message.author.bot) return;
  
    // Ignore messages not starting with the prefix (in config.json)
    if (message.content.indexOf(client.config.prefix) !== 0) return;
  
    // Our standard argument/command name definition.
    const args = message.content.slice(client.config.prefix.length).trim().split(/ +/g);
    const command = args.shift().toLowerCase();
  
    // Grab the command data from the client.commands Enmap
    const cmd = client.commands.get(command);
  
    // If that command doesn't exist, silently exit and do nothing
    if (!cmd) return;
  
    // Run the command
    cmd.run(client, message, args);
};
```

**Comment by Androz2091** [comment]
Hello,
What are you trying to do? Adding commands to the bot?

**Comment by SrPeterr** [comment]
Hi!
I was messing around lol trying to but it on my own Bot, but, I separated it to two bots, Giveways bot and normal bot :P
Anyways, all solved!

**Comment by Androz2091** [comment]
> Does this mean, that if the user doesn't have the "MANAGE_MESSAGES" or the Role "Giveaways" he cant start,stop, reroll a Giveaway?

Yes, that's it.

> And how does the "noWinner" I did a test one, with my account and a friend, and got no valid winners :(

If you and your friend were administrators, that's normal. Try with a regular account without any permission that could identify you as a staff member.

**Comment by Androz2091** [comment]
Closed due to inactivity
