### ISSUE TITLE
Problème de création du giveaway

### ISSUE THREAD

**Issue by MatthieuLeboeuf** [Androz2091/giveaways-bot#3]
Bonjour,

j'ai un problème en utilisant votre package:

https://cdn.discordapp.com/attachments/636141139052724274/667078142510497802/unknown.png

https://cdn.discordapp.com/attachments/636141139052724274/667078420219428877/unknown.png

vous pouvez m'aider ?
Matthieu

**Comment by Androz2091** [comment]
@MatthieuLeboeuf bonjour, c'est un problème concernant ce bot, ou un problème concernant https://npmjs.com/discord-giveaways ?
