### ISSUE TITLE
Whoever hosts the draw is not drawn if he is the only one to participate in the draw and the draw starts with 0 winners

### ISSUE THREAD

**Issue by powerflips** [Androz2091/giveaways-bot#30]
I am testing the project and I came across some problems, Whoever hosts the draw is not drawn if he is the only one to participate in the draw, and the draw starts with 0 winners.

If you start the draw with 0 winners at the end of the time, he does not draw anyone, the draw could not start with 0 winners and the person who creates the draw must be drawn if he is the only one to participate in the draw.

**Comment by Androz2091** [comment]
Hello @powerflips. I think the person who creates the giveaway is not drawn because it's an administrator. Also, the giveaway is drawn even if there is no participants, but it should display an error message.

**Comment by powerflips** [comment]
yes, but if he is clumsy, he can make a draw with 0 participants a week, many people participate in the draw and the error is e sampled at the end of the session .. that is, everyone who participated a week does not get the draw  because of a lack of attention from the host that put 0 participants.  besides some places like Discord Bot List, are not accepting the bot with this problem
