### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by boingfromdiscord** [Androz2091/giveaways-bot#31]
Maybe have the message link of the giveaway when giveaway ends?

**Comment by boingfromdiscord** [comment]
Also you can use the easy-me module so you can do something like 1m2s

**Comment by Androz2091** [comment]
> Maybe have the message link of the giveaway when giveaway ends?
You can use `giveaway.message.url` (using the `giveawayEnded` event)

**Comment by boingfromdiscord** [comment]
Wdym?
