### ISSUE TITLE
The storage file is not properly formatted

### ISSUE THREAD

**Issue by boingfromdiscord** [Androz2091/giveaways-bot#32]
Im getting this error `(node:1688) UnhandledPromiseRejectionWarning: SyntaxError: The storage file is not properly formatted (giveaways is not an array).
    at GiveawaysManager.getAllGiveaways (/Users/PL/Desktop/Tyler Works-DONTrash/ducky/node_modules/discord-giveaways/src/Manager.js:300:27)
    at async GiveawaysManager._init (/Users/PL/Desktop/Tyler Works-DONTrash/ducky/node_modules/discord-giveaways/src/Manager.js:387:30)
(node:1688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1688) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Androz2091** [comment]
Hello @boingfromdiscord,
Did you create the storage file (`giveaways.json`) yourself?

**Comment by boingfromdiscord** [comment]
yes sorry I had it in the wrong place

**Comment by Androz2091** [comment]
👍
