### ISSUE TITLE
spam?

### ISSUE THREAD

**Issue by boingfromdiscord** [Androz2091/giveaways-bot#33]
<img width="691" alt="Screen Shot 2020-05-27 at 11 22 22 AM" src="https://user-images.githubusercontent.com/62665535/83039616-62735a00-a00c-11ea-92bb-2b531b299f42.png">

**Comment by boingfromdiscord** [comment]
**Update**
when ever I use the command it spams

**Comment by Androz2091** [comment]
Hello @boingfromdiscord,
Did you upragde to v4.1.5?

**Comment by boingfromdiscord** [comment]
of the npm package? because I just got it yesterday @Androz2091

**Comment by Androz2091** [comment]
Yes. Can you try to update it?

**Comment by boingfromdiscord** [comment]
ok

**Comment by boingfromdiscord** [comment]
Hello @Androz2091 ?
