### ISSUE TITLE
It's not working.

### ISSUE THREAD

**Issue by Akurejs** [Androz2091/giveaways-bot#44]
I'm using the project, people make the giveaway it works for a while and then it freezes and stops counting the time, in the file giveaway.json the giveaway information from those servers that simply froze doesn't even exist.
And when you use the index with quick.db it's the same thing

**Comment by tovade** [comment]
did you define everything

**Comment by DamaraNadhra** [comment]
![image](https://user-images.githubusercontent.com/70007198/92585053-aa1da900-f2be-11ea-8940-71c9a057440e.png)
Hello why when the bot crashed the giveaway wont restart? I meant after bot crashed the giveaway will stop, can someone fix this? I've already followed the tutorial

**Comment by needhamgary** [comment]
@DamaraNadhra heroku doesn't support JSON files, which is where your giveaway is stored. The entire file is erased on every restart, therefore your bot doesn't know that it is supposed to have a giveaway.

**Comment by needhamgary** [comment]
@Akurejs consider switching to mongo db

**Comment by Androz2091** [comment]
Use https://androz2091.fr/discord to get help
