### ISSUE TITLE
Unexpected Token "!"

### ISSUE THREAD

**Issue by Coocktail** [Androz2091/giveaways-bot#50]

**Comment by Coocktail** [comment]
f(!message.member.hasPermission('MANAGE_MESSAGES')  && !message.member.roles.cache.some((r) => r.name === "Giveaways")) {

SyntaxError: Unexpected token '!'

**Comment by NicoHd105** [comment]
Ahm I don't think that this has anything to do with the module...

**Comment by Coocktail** [comment]
ok

**Comment by Coocktail** [comment]
but can u still help me
fix it

**Comment by Coocktail** [comment]
and one more thing
i just want to check for the manage messages permission not the role

**Comment by NicoHd105** [comment]
if (!message.member.permissions.has("MANAGE_CHANNELS")
this is for v12

**Comment by NicoHd105** [comment]
and now close this issue

**Comment by Coocktail** [comment]
Ok

**Comment by Coocktail** [comment]
The solution didnt work for me
I still get the same error

**Comment by NicoHd105** [comment]
Beuh that line would work 100% so idk what is wrong then are you sure it was this line: `if(!message.member.hasPermission('MANAGE_MESSAGES') && !message.member.roles.cache.some((r) => r.name === "Giveaways")) {`
That caused the 1st error?

**Comment by boingfromdiscord** [comment]
your missing a ) `if (!message.member.hasPermission('MANAGE_MESSAGES))`

**Comment by Coocktail** [comment]
Yea sorry
