### ISSUE TITLE
Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by HDProduction010** [Androz2091/giveaways-bot#57]
This is the error that I am getting

(node:18101) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'start' of undefined
    at Object.module.exports.run (/home/Aresentic/commands/Fun/gstart.js:39:31)
    at Client.<anonymous> (/home/Aresentic/handlers/JoinAndLeaves/message.js:21:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18101) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18101) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by needhamgary** [comment]
Sounds like you are missing a required file possibly... Can you show your code?

**Comment by HDProduction010** [comment]
Ok so I'm isolating the commands and using a command handler to implement it into my bot

**Comment by HDProduction010** [comment]
But here it is

**Comment by needhamgary** [comment]
You either didn't post the code itself or no one else can see it. Try using a code block instead of posting a link??

**Comment by needhamgary** [comment]
```
Code here
```

**Comment by HDProduction010** [comment]
Sorry about that give me a second

**Comment by HDProduction010** [comment]
let Discord = require('discord.js');
const ms = require('ms');
const { GiveawaysManager } = require("discord-giveaways");
module.exports.run = async (client, message, args) => {

    // If the member doesn't have enough permissions
    if(!message.member.hasPermission('MANAGE_MESSAGES') && !message.member.roles.cache.some((r) => r.name === "Giveaways")){
        return message.channel.send(':x: You need to have the manage messages permissions to start giveaways.');
    }

    // Giveaway channel
    let giveawayChannel = message.mentions.channels.first();
    // If no channel is mentionned
    if(!giveawayChannel){
        return message.channel.send(':x: You have to mention a valid channel!');
    }

    // Giveaway duration
    let giveawayDuration = args[1];
    // If the duration isn't valid
    if(!giveawayDuration || isNaN(ms(giveawayDuration))){
        return message.channel.send(':x: You have to specify a valid duration!');
    }

    // Number of winners
    let giveawayNumberWinners = args[2];
    // If the specified number of winners is not a number
    if(isNaN(giveawayNumberWinners) || (parseInt(giveawayNumberWinners) <= 0)){
        return message.channel.send(':x: You have to specify a valid number of winners!');
    }

    // Giveaway prize
    let giveawayPrize = args.slice(3).join(' ');
    // If no prize is specified
    if(!giveawayPrize){
        return message.channel.send(':x: You have to specify a valid prize!');
    }

    // Start the giveaway
    client.giveawaysManager.start(giveawayChannel, {
        // The giveaway duration
        time: ms(giveawayDuration),
        // The giveaway prize
        prize: giveawayPrize,
        // The giveaway winner count
        winnerCount: giveawayNumberWinners,
        // Who hosts this giveaway
        hostedBy: client.config.hostedBy ? message.author : null,
        // Messages
        messages: {
            giveaway: (client.config.everyoneMention ? "@everyone\n\n" : "")+"🎉🎉 **GIVEAWAY** 🎉🎉",
            giveawayEnded: (client.config.everyoneMention ? "@everyone\n\n" : "")+"🎉🎉 **GIVEAWAY ENDED** 🎉🎉",
            timeRemaining: "Time remaining: **{duration}**!",
            inviteToParticipate: "React with 🎉 to participate!",
            winMessage: "Congratulations, {winners}! You won **{prize}**!",
            embedFooter: "Giveaways",
            noWinner: "Giveaway cancelled, no valid participations.",
            hostedBy: "Hosted by: {user}",
            winners: "winner(s)",
            endedAt: "Ended at",
            units: {
                seconds: "seconds",
                minutes: "minutes",
                hours: "hours",
                days: "days",
                pluralS: false // Not needed, because units end with a S so it will automatically removed if the unit value is lower than 2
            }
        }
    });

    message.channel.send(`Giveaway started in ${giveawayChannel}!`);

};

module.exports.help = {
  name: "create",
  description: "This command module creates a Giveaway",
  usage: `<prefix>create`,
  accessableby: "Members",
  aliases: [""]
};

**Comment by needhamgary** [comment]
You may also need to check the handler that's pulling in your cmd

**Comment by HDProduction010** [comment]
it is

**Comment by HDProduction010** [comment]
I can tell because it will trigger the "error" send messages to the channel where there isnt the full command

**Comment by needhamgary** [comment]
Okay do you have client giveaway manager defined in your <index> file?

**Comment by HDProduction010** [comment]
const { GiveawaysManager } = require("discord-giveaways");

**Comment by HDProduction010** [comment]
Where else would I define it

**Comment by HDProduction010** [comment]
Add me on discord and lets talk over there. HD#1817

**Comment by needhamgary** [comment]
You need to define `client.giveawaysManager` after that

**Comment by HDProduction010** [comment]
so 

let or const

**Comment by HDProduction010** [comment]
What one should I use

**Comment by needhamgary** [comment]
I have to get back to work.

**Comment by HDProduction010** [comment]
Dang ok let me know what I need to do when you are available

**Comment by needhamgary** [comment]
I added you on discord

**Comment by c-apex** [comment]
Sorry to revive, but was the fix ever posted publicly?
