### ISSUE TITLE
The Bot cannot restart the giveaway

### ISSUE THREAD

**Issue by DamaraNadhra** [Androz2091/giveaways-bot#58]
![image](https://user-images.githubusercontent.com/70007198/93540822-064b9180-f97f-11ea-8208-c8d70d6fe980.png)
after this error the time is freezed and giveaway stopped, I always got this problem whenever I put long duration giveaway (24h, 10h) any idea to fix 

FYI: I followed any tutorials to make giveaway bot

**Comment by needhamgary** [comment]
This giveaway system saves to a .JSON file and heroku doesn't support those files. Therefore every time the bot restarts in any way, that file gets erased completely. 2 solutions... 1. Switch it over to an online database or 2. Put your bot on a vps instead of junkify heroku

**Comment by DamaraNadhra** [comment]
how to make giveaway saved to db and make it read

**Comment by needhamgary** [comment]
Yes but not on heroku... Quick.db still uses . JSON file

**Comment by DamaraNadhra** [comment]
Any guide to change storage location? or maybe another hosting website

**Comment by needhamgary** [comment]
Set up mongodb

**Comment by Androz2091** [comment]
Use https://androz2091.fr/discord for more help
