### ISSUE TITLE
Getting an error in the code for Giveaway.js

### ISSUE THREAD

**Issue by BigShotsGaming** [Androz2091/giveaways-bot#66]
**TypeError: guild.member is not a function
  at C:\Users\gamer\Desktop\Big Shot Moderation\node_modules\discord-giveaways\src\Giveaway.js:294:32**

Not sure if this needs to be updated or not. This only throws when a giveaway ends and tries to post the winner

**Comment by Androz2091** [comment]
Should be fixed with the latest release
