### ISSUE TITLE
Add "Hosted by" under the timer

### ISSUE THREAD

**Issue by SGAHJDGAJHDGSA** [Androz2091/giveaways-bot#7]
As a suggestion, you should be able to add a field under the timmer that says who the giveaway is hosted by. Thanks again

**Comment by SGAHJDGAJHDGSA** [comment]
So will this suggestion be added?

**Comment by Androz2091** [comment]
Yes, when I will be able make it (or someone can open a pr)

**Comment by SGAHJDGAJHDGSA** [comment]
Whats a pr?

**Comment by Androz2091** [comment]
A pull request, search on google you will find informations.

**Comment by Androz2091** [comment]
Implemented
