### ISSUE TITLE
[BUGS] When time of giveaway < 10 it bugs

### ISSUE THREAD

**Issue by BeamKunGzMARK** [Androz2091/giveaways-bot#70]
Suchas 
&sg 10s 1 Awesome prize!
it will bug don't roll

**Comment by dylanjamesdev** [comment]
Happened to me also, can confirm.

**Comment by Androz2091** [comment]
@BeamKunGzMARK do you have an error in the terminal?

**Comment by BeamKunGzMARK** [comment]
No have any error in terminal and I'm very sure for it will bug when user set time of giveaway < 10 sec 
It will didn't roll

**Comment by BeamKunGzMARK** [comment]
I try around 20 round to test for it will bug and yea it will bugs

**Comment by Androz2091** [comment]
@BeamKunGzMARK can you run `npm install discord-giveaways@latest`?

**Comment by BeamKunGzMARK** [comment]
@Androz2091 ok I'll try

**Comment by Androz2091** [comment]
@BeamKunGzMARK is this resolved? (when you tried)
