### ISSUE TITLE
The Giveaway start Freezing .

### ISSUE THREAD

**Issue by Zaid-maker** [Androz2091/giveaways-bot#9]
After that Update The Giveaways stop working and freeze and put this error in console `Cannot find giveaway with id ...` when we try to end the giveaway it do nothing. i have a bot top.gg and getting so many requests to fix this problem the whole problem is with end command

**Comment by Zaid-maker** [comment]
Please help me i have so much downfall.

**Comment by Androz2091** [comment]
> After that update

Which update?

**Comment by Zaid-maker** [comment]
@Androz2091 The recent Update in the discord-giveaways Package

**Comment by Androz2091** [comment]
So the giveaway freezes even if you don't use the end command?

**Comment by Zaid-maker** [comment]
yes, many time

**Comment by Zaid-maker** [comment]
@Androz2091 Please do something

**Comment by Androz2091** [comment]
I couldn't reproduce the bug...
